version: "3.6"
services:

  openindoor-app:
    build:
      context: .
    image: openindoor/openindoor-app
    command: yarn serve --port 80
    # command: yarn lint

    volumes:
    - ./src:/openindoor-app/src
    - ./Caddyfile:/etc/caddy/Caddyfile
    environment:      
      API_URL: http://api-sandbox.openindoor.io
      APP_URL: http://app-sandbox.openindoor.io
    ports:
    - 8080:80
