version: "3.6"
services:

  openindoor-app:
    build:
      context: .
    image: openindoor/openindoor-app
    # command: yarn serve --port 80
    volumes:
    - ./openindoor-app/src:/openindoor-app/src
    environment:
      API_DOMAIN_NAME: ${API_DOMAIN_NAME}
      API_URL: http://${API_DOMAIN_NAME}
    ports:
    - 8080:80
